### PR TITLE
Add new baseline /organizations endpoint tests

### PR DESCRIPTION
**Pull request by jhodapp**
## Description
This PR seeks to fill out blackbox tests of all the major operations one can do with our /organizations endpoint.

### Changes
* Moves the logging initialization functionality into its own module/struct called `logging::Logger` - this is to make it possible to use the logger in these (and other) tests
* Creates a test HTTP client/server struct and impl to reuse for blackbox testing endpoints
* Adds a test ensuring all organizations are returned by a GET with no ID specified
* Adds a test ensuring a specific organization instance can be deleted by specifying its ID with DELETE
* Adds a test ensuring that it's possible to create a new organization instance using POST
* Adds a test ensuring a specific organization instance can be updated by specifying its ID with PUT

### Testing Strategy
1. Run `cargo test` at the root of the source tree and observe these 4 new tests pass

Expected output:

```sh
running 1 test
21:06:53 [INFO] Running tests for "entity_api" crate

21:06:54 [INFO] All "entity_api" tests completed successfully.

21:06:54 [INFO]
running 1 test
test organization::tests::find_all_returns_a_list_of_records_when_present ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


21:06:54 [INFO]     Finished test [unoptimized + debuginfo] target(s) in 0.09s
     Running unittests src/lib.rs (target/debug/deps/entity_api-1c2029c6d4569097)
   Doc-tests entity_api

21:06:54 [INFO] Running tests for "web" crate

21:06:54 [INFO] All "web" tests completed successfully.

21:06:54 [INFO]
running 5 tests
test router::organization_endpoints_tests::read_returns_all_organizations ... ok
test router::organization_endpoints_tests::read_returns_expected_json_for_specified_organization ... ok
test router::organization_endpoints_tests::update_an_organization_specified_by_id ... ok
test router::organization_endpoints_tests::create_new_organizations_successfully ... ok
test router::organization_endpoints_tests::delete_two_organization_specified_by_two_ids ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s
```

### Concerns
None

### CODE REVIEW

**Comment by jhodapp** [comment]
Going back to draft PR status because I want to consolidate the repetitious Reqwest client code into a reusable structure.

**Review by calebbourg — COMMENTED** [review]
Tests look great! Thank you for adding these. I just had one question so far.

**Review by qafui — APPROVED** [review]
Nice clean-up!

**Review by calebbourg — APPROVED** [review]

**Comment by jhodapp** [comment]
> Nice clean-up!

Why thank you! 😊

**Pull request merged**
